//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCentre_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthCentre_Entities : DbContext
    {
        public HealthCentre_Entities()
            : base("name=HealthCentre_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<choroby> choroby { get; set; }
        public virtual DbSet<diagnozy> diagnozy { get; set; }
        public virtual DbSet<lekarze> lekarze { get; set; }
        public virtual DbSet<lekarze_specjalisci> lekarze_specjalisci { get; set; }
        public virtual DbSet<medykamenty> medykamenty { get; set; }
        public virtual DbSet<medykamenty_zalecone> medykamenty_zalecone { get; set; }
        public virtual DbSet<nazwy_specjalizacji> nazwy_specjalizacji { get; set; }
        public virtual DbSet<pacjenci> pacjenci { get; set; }
        public virtual DbSet<porady_lekarskie> porady_lekarskie { get; set; }
    }
}
