//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCentre
{
    using System;
    using System.Collections.Generic;
    
    public partial class lekarze_specjalisci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lekarze_specjalisci()
        {
            this.porady_lekarskie = new HashSet<porady_lekarskie>();
        }
    
        public long id_lekSpecjalista { get; set; }
        public long id_specjalizacji { get; set; }
        public long id_lekarza { get; set; }
    
        public virtual lekarze lekarze { get; set; }
        public virtual nazwy_specjalizacji nazwy_specjalizacji { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<porady_lekarskie> porady_lekarskie { get; set; }
    }
}
