//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCentre
{
    using System;
    using System.Collections.Generic;
    
    public partial class medykamenty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medykamenty()
        {
            this.medykamenty_zalecone = new HashSet<medykamenty_zalecone>();
        }
    
        public long id_medykamentu { get; set; }
        public string nazwa_medykamentu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medykamenty_zalecone> medykamenty_zalecone { get; set; }
    }
}
