//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCentre_
{
    using System;
    using System.Collections.Generic;
    
    public partial class medykamenty_zalecone
    {
        public long id_zalecenia { get; set; }
        public long id_medykamentu { get; set; }
        public long id_diagnozy { get; set; }
        public string dawkowanie { get; set; }
    
        public virtual diagnozy diagnozy { get; set; }
        public virtual medykamenty medykamenty { get; set; }
    }
}
