//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCentre
{
    using System;
    using System.Collections.Generic;
    
    public partial class nazwy_specjalizacji
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nazwy_specjalizacji()
        {
            this.lekarze_specjalisci = new HashSet<lekarze_specjalisci>();
        }
    
        public long id_specjalizacji { get; set; }
        public string nazwa_specjalizacji { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lekarze_specjalisci> lekarze_specjalisci { get; set; }
    }
}
